listen 80;
listen [::]:80;
    # everything else is in the main config, there's nothing specific for HTTP
    # except not listening with SSL
    # Note: default_server lives in the catch-all block at the bottom of default.conf
